# Generated by Django 4.1.7 on 2023-10-09 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollectionmovies',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercollectionmovies',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercollections',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercollections',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
