# Generated by Django 4.1.7 on 2023-10-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_rename_jwttokengeneratedtoken_userjwtgeneratedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJWTGeneratedToken',
        ),
    ]
