# Generated by Django 4.1.7 on 2023-10-10 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_alter_usercollections_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionmovies',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercollections',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
