# Generated by Django 4.1.7 on 2023-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0009_alter_usercollectionmovies_collection_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionmovies',
            name='genres',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
