# Generated by Django 4.1.7 on 2023-10-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0011_usercollectionrequestcountapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollectionrequestcountapi',
            name='user_map',
        ),
    ]
